default: &default
  adapter: postgresql

  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  
  encoding: unicode
  pool: 5

  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: ib_dev

test:
  <<: *default
  database: ib_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
