default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/dev_db.sqlite3

test:
  <<: *default
  database: db/test_db.sqlite3

production:
  <<: *default
  database: db/production_db.sqlite3
