default: &default
  adapter: postgresql

  host: localhost
  port: 7474
  
  encoding: unicode
  pool: 5

  username: image_board
  password: 12345

development:
  <<: *default
  database: db_dev

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: db_production
