source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'

# Assets
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '~> 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'foundation-rails'
gem 'foundation_rails_helper'

gem 'jquery-rails'
gem 'turbolinks'

gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]

# Image uploading
gem 'carrierwave'

# Image processing
gem 'mini_magick'

# Tagging system
gem 'acts-as-taggable-on'

gem 'will_paginate'
gem 'will_paginate-foundation'

gem 'thin', '~> 1.6.2'
